/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as DashboardImport } from './routes/dashboard'
import { Route as CreateImport } from './routes/create'
import { Route as IndexImport } from './routes/index'
import { Route as DashboardIndexImport } from './routes/dashboard/index'
import { Route as AssignmentsIndexImport } from './routes/assignments/index'
import { Route as DashboardUsersImport } from './routes/dashboard/users'
import { Route as DashboardOverviewImport } from './routes/dashboard/overview'
import { Route as DashboardEmployeesImport } from './routes/dashboard/employees'
import { Route as DashboardAssignmentsImport } from './routes/dashboard/assignments'
import { Route as AssignmentsAssignmentIdImport } from './routes/assignments/$assignmentId'
import { Route as AuthLayoutSignupImport } from './routes/_auth-layout.signup'
import { Route as AuthLayoutLoginImport } from './routes/_auth-layout.login'

// Create Virtual Routes

const AuthLayoutLazyImport = createFileRoute('/_auth-layout')()

// Create/Update Routes

const AuthLayoutLazyRoute = AuthLayoutLazyImport.update({
  id: '/_auth-layout',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/_auth-layout.lazy').then((d) => d.Route))

const DashboardRoute = DashboardImport.update({
  path: '/dashboard',
  getParentRoute: () => rootRoute,
} as any)

const CreateRoute = CreateImport.update({
  path: '/create',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const DashboardIndexRoute = DashboardIndexImport.update({
  path: '/',
  getParentRoute: () => DashboardRoute,
} as any)

const AssignmentsIndexRoute = AssignmentsIndexImport.update({
  path: '/assignments/',
  getParentRoute: () => rootRoute,
} as any)

const DashboardUsersRoute = DashboardUsersImport.update({
  path: '/users',
  getParentRoute: () => DashboardRoute,
} as any)

const DashboardOverviewRoute = DashboardOverviewImport.update({
  path: '/overview',
  getParentRoute: () => DashboardRoute,
} as any)

const DashboardEmployeesRoute = DashboardEmployeesImport.update({
  path: '/employees',
  getParentRoute: () => DashboardRoute,
} as any)

const DashboardAssignmentsRoute = DashboardAssignmentsImport.update({
  path: '/assignments',
  getParentRoute: () => DashboardRoute,
} as any)

const AssignmentsAssignmentIdRoute = AssignmentsAssignmentIdImport.update({
  path: '/assignments/$assignmentId',
  getParentRoute: () => rootRoute,
} as any)

const AuthLayoutSignupRoute = AuthLayoutSignupImport.update({
  path: '/signup',
  getParentRoute: () => AuthLayoutLazyRoute,
} as any)

const AuthLayoutLoginRoute = AuthLayoutLoginImport.update({
  path: '/login',
  getParentRoute: () => AuthLayoutLazyRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/create': {
      preLoaderRoute: typeof CreateImport
      parentRoute: typeof rootRoute
    }
    '/dashboard': {
      preLoaderRoute: typeof DashboardImport
      parentRoute: typeof rootRoute
    }
    '/_auth-layout': {
      preLoaderRoute: typeof AuthLayoutLazyImport
      parentRoute: typeof rootRoute
    }
    '/_auth-layout/login': {
      preLoaderRoute: typeof AuthLayoutLoginImport
      parentRoute: typeof AuthLayoutLazyImport
    }
    '/_auth-layout/signup': {
      preLoaderRoute: typeof AuthLayoutSignupImport
      parentRoute: typeof AuthLayoutLazyImport
    }
    '/assignments/$assignmentId': {
      preLoaderRoute: typeof AssignmentsAssignmentIdImport
      parentRoute: typeof rootRoute
    }
    '/dashboard/assignments': {
      preLoaderRoute: typeof DashboardAssignmentsImport
      parentRoute: typeof DashboardImport
    }
    '/dashboard/employees': {
      preLoaderRoute: typeof DashboardEmployeesImport
      parentRoute: typeof DashboardImport
    }
    '/dashboard/overview': {
      preLoaderRoute: typeof DashboardOverviewImport
      parentRoute: typeof DashboardImport
    }
    '/dashboard/users': {
      preLoaderRoute: typeof DashboardUsersImport
      parentRoute: typeof DashboardImport
    }
    '/assignments/': {
      preLoaderRoute: typeof AssignmentsIndexImport
      parentRoute: typeof rootRoute
    }
    '/dashboard/': {
      preLoaderRoute: typeof DashboardIndexImport
      parentRoute: typeof DashboardImport
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren([
  IndexRoute,
  CreateRoute,
  DashboardRoute.addChildren([
    DashboardAssignmentsRoute,
    DashboardEmployeesRoute,
    DashboardOverviewRoute,
    DashboardUsersRoute,
    DashboardIndexRoute,
  ]),
  AuthLayoutLazyRoute.addChildren([
    AuthLayoutLoginRoute,
    AuthLayoutSignupRoute,
  ]),
  AssignmentsAssignmentIdRoute,
  AssignmentsIndexRoute,
])

/* prettier-ignore-end */
